### ISSUE TITLE
Clarification: Php = Snippets?

### ISSUE THREAD

**Issue by matdave** [alienbuild/modx-opencart#1]
I just wanted to clarify, is this a library of snippets, or how do you currently integrate it?

**Comment by matdave** [comment]
according to ReadMe it's just a bunch of snippets, so that's the assumption ... sorry didn't read the first line, lol.

**Comment by alienbuild** [comment]
Sorry @matdave I've only just seen this! I assume you figured it out though since posting haha

**Comment by matdave** [comment]
No worries, I have like 80 repo's I am following and always miss things too.
